name: Bug Report
description: Report a bug
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report please check that your issue was not already discussed in the following:

        * [Issues](https://github.com/KatsuteDev/GitHub-Center/issues?q=is%3Aissue+is%3Aopen+label%3Abug%2C%22critical+bug%22)

        Please also check that:

        * This is actually a bug and not a feature.
        * You are running the latest version.

  - type: input
    attributes:
      label: Operating System
    validations:
      required: true

  - type: input
    attributes:
      label: Browser
    validations:
      required: true

  - type: input
    attributes:
      label: Extension Version
    validations:
      required: true

  - type: textarea
    attributes:
      label: Issue
      description: |
        Explain the issue and add a screenshot.
    validations:
      required: true