name: npm CI

on:
  workflow_dispatch:
  schedule:
    - cron: 0 11 * 1-2,11-12 1
    - cron: 0 10 * 3-10 1
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]

jobs:
  npm_ci:
    name: npm CI
    uses: KatsuteDev/Workflows/.github/workflows/npm.ci.yml@main